language: go

go:
  - 1.13
  - 1.14

os:
  - linux
  - osx
  - windows

script:
  - go clean -testcache
  - go test -v -cover ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: eCmy1Xy+zcr0Duli4WEZfCBDMupwqJ/F7bZ5Da8TzOOJIzl/+kJBr58haCM8xlkzfv5dVQ4P7QhDbPVs98eQQgmDOJcZ0rrvgwyy/0+fBt4i1zMAuc9Dt6E8yxoMvM7FT5Wo4YQidoTb9f+sCUfV5uEncPTdaXqomqfMWHUmwW5Jh0pXYUlvUTI8q4RiBxcR9MJ9JDM38Lxtx49S8Gfq9sbvAJN9EcYF9V2z9rQMM0HtpaL9Q1HN36q6DKOCA4OeT9cVJPtEuz5esMcqgMbD09YAaI/SoizNQJxgCiVhzFhwXMX51AaAazRDYRWf0xVK7Q48+fq4fI+aLwfc018H+Wyv87GC47Ipqha1S/C4Z1KGA7OUoykMgTCavp+aQwbAiGX9RMKPfpk1iDcv+L3AQWG1BesMeCPNmPFTvAGBccQmh9Fh89wEimQ+S5P7oLgEJVYQRZd2f+SAC1co663QVpf15z4HVNVd0hs4fQYORTmE8fkS6xeRC3ePFfMRgqHcnvvmuOTVhrr8ILb+uxyDulwI4a43MWy8kGo9lFqRecN13BLDv8IAm3D5/mFtTcAIHbc1IbUZDdnfwM1Sn/U5v2p0kWCPLetteyIuQqpD4bIGPTQ7z2wiiCxoE8KI4udtDCCnE873NxgTMsPv8niqcCiRdB4wvAN1A4qs973dP9U=
